# Generated by Django 6.0.4 on 2026-07-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('style', models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('CASUAL', 'Casual'), ('RESPECT-TONED', 'Respect-Toned')], max_length=15)),
                ('output', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
